name = "file-server"
main = "src/index.ts"
compatibility_date = "2026-06-08"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "file-server-bucket"

[triggers]
crons = ["0 3,15 * * *"]

[vars]
MAX_UPLOAD_SIZE = "262144000"
RATE_LIMIT_PER_MINUTE = "60"
ALLOWED_ORIGIN = "https://kalpha.mmv.kr"
ADMIN_ID = "kalpha"
ADMIN_PW_HASH = "5683fc86d60e7346dfa491217c0180215d9d813743c03df0daa0b6b4488fc7d9"
