name = "file-server"
main = "src/index.ts"
compatibility_date = "2026-06-08"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "file-server-bucket"

[triggers]
crons = ["0 0,12 * * *"]

[vars]
MAX_UPLOAD_SIZE = "262144000"
RATE_LIMIT_PER_MINUTE = "60"
ALLOWED_ORIGIN = "https://kalpha.mmv.kr"
ADMIN_ID = "kalpha"
ADMIN_PW_HASH = "pbkdf2:100000:LUejJphS82naqWbTWxmp8A:qHfyd5rbebyiJYsEWDgbN4Evc2xAlFCB1Z0rlPmr6gk"
SHARE_BASE_URL = "https://file.kalpha.kr"
